### ISSUE TITLE
images loaded over insecure http on secure https

### ISSUE THREAD

**Issue by Pappmann** [NodeBB-Community/nodebb-plugin-emoji-extended#1]
missing feature to load emoji images over HTTPS

Browser feedback:

      'http://my-domain.com/' was loaded over HTTPS, but requested an insecure image 'http://my-domain.com/plugins/nodebb-plugin-emoji-extended/images/grin.png'. This content should also be served over HTTPS.

**Comment by frissdiegurke** [comment]
please check your *config.json* for the `url` property ;-)

**Comment by Pappmann** [comment]
thanks, that was it :smiley:
