### ISSUE TITLE
Not NodeBB 1.2.1 Compatible

### ISSUE THREAD

**Issue by deiden26** [NodeBB-Community/nodebb-plugin-emoji-extended#16]
I have NodeBB 1.2.1 installed, and I am unable to access emojis in the default composer. The editor toolbar button is not there, the autocomplete doesn't work, and the parsing doesn't work.

**NodeBB 1.1.2**
![screen shot 2016-10-20 at 7 08 58 pm](https://cloud.githubusercontent.com/assets/2993523/19584361/beeb010a-96f8-11e6-9654-425333864658.png)

**NodeBB 1.2.1**
![screen shot 2016-10-20 at 7 09 10 pm](https://cloud.githubusercontent.com/assets/2993523/19584363/c1771346-96f8-11e6-96fe-4ada86f9fea1.png)

**Comment by ghost** [comment]
It's been noticed it does not work with nodejs v6; might this be the reason here?

**Comment by deiden26** [comment]
Yes, that is likely the cause. I was running NodeBB 1.2.1 on nodejs 6.7.0. Should I just use v4?

**Comment by deiden26** [comment]
I just downgraded my node version to v4.6.1 . The issue is persisting

**Comment by jobukkit** [comment]
I have 1.2.1, the plugin works fine...

**Comment by deiden26** [comment]
That's interesting. Here is all of the relevant info I can think of about the instance I am running locally
- **NodeBB version:** 1.2.1
- **NodeBB git hash**: dfc8ceef9e4fe737f489eb8517c7477300c37d3f
- **Database:** Mongodb 3.2.10
- **NodeJS version:** 4.6.1
- **nodebb-plugin-emoji-one version:** 1.1.5
- **nodebb-plugin-emoji-extended version:** 1.1.1

Note: there are no errors in my browser's console and NodeBB's logs are clear

**Comment by NormandoHall** [comment]
Any news? Something

**Comment by jobukkit** [comment]
I'm not using any plugin anymore. Just let people use Unicode emoji's.

**Comment by deiden26** [comment]
I have not had a chance to investigate further, but I plan to check how this plugin works when run on the latest version on nodeBB (currently 1.4.1)

**Comment by psychobunny** [comment]
It's highly recommend that you upgrade to latest anyways (and the plugin should work there) for the latest security fixes if anything. I think I'll close this, feel free to ping if it's still an issue

**Comment by jimmykane** [comment]
I have the exact same issue.

**Comment by jimmykane** [comment]
I have the exact same issue.  Any suggestions ?

**Comment by julianlam** [comment]
@jimmykane Please use `nodebb-plugin-emoji` instead of `emoji-extended`. Thanks.

**Comment by jimmykane** [comment]
@julianlam  thanks but there is no `nodebb-plugin-emoji` in the plugin listing.

**Comment by jimmykane** [comment]
@julianlam  I have the following installed. 
<img width="865" alt="screen shot 2017-11-14 at 16 28 36" src="https://user-images.githubusercontent.com/1268723/32788233-f62b11c6-c958-11e7-942e-ec5d05f1c9d0.png">

Somehow now this works. 

However, I am very curious why I don't have the one suggested by you neither it is available in the ones that I can install. 

Thanks for the effort!

**Comment by julianlam** [comment]
Ah it is not published yet. You can install it with `npm i http://github.com/nodebb/nodebb-plugin-emoji#master`

**Comment by jimmykane** [comment]
@julianlam as I don't have access to the machine (I am just an admin in that forum) I think ill have to wait. 
Should I then remove the current ones (extended and one) and install the one suggested? 

Thanks a lot!
