### ISSUE TITLE
accepting an autocomplete does not update the composer's preview

### ISSUE THREAD

**Issue by BenLubar** [NodeBB-Community/nodebb-plugin-emoji-extended#2]
Demonstration: https://www.youtube.com/watch?v=wkZggOpw0bo

**Comment by julianlam** [comment]
You know... I've noticed this for quite awhile but it never really occurred to me to fix it, since it's only a minor issue. I suppose if you see it enough times you stop noticing it :laughing:

**Comment by julianlam** [comment]
To fix, either call `.trigger('input')` on the textarea, or `require(['composer/preview'])` and call .render(), passing in the textarea element

**Comment by frissdiegurke** [comment]
I've merged and fixed (the variable `$textarea` actually was no `jQuery` object o_O).

However, this just regards clicks within the modal.

For the original demonstration (trigger update after autocompletion) I think this belongs into the core (for chats, into default composer for posts) @julianlam . 
According to [this line](https://github.com/yuku-t/jquery-textcomplete/blob/master/src/completer.js#L187) you could watch for either of those events in addition to `"input"`.

**Comment by frissdiegurke** [comment]
Moved to https://github.com/NodeBB/nodebb-plugin-composer-default/issues/27
