### ISSUE TITLE
Emoji Extended get error when clicking update files on v1.5.0

### ISSUE THREAD

**Issue by fuhaiq** [NodeBB-Community/nodebb-plugin-emoji-extended#20]
Everything goes well except emoji extended plugin.

When I clicking update files
![0zjpf6h](https://cloud.githubusercontent.com/assets/5200755/25884699/e49e8af2-3586-11e7-9e9c-ffe6bc32fecf.png)
Worse is this cause server shutdown

> Invalid or unsupported zip format. No END header found

please refer to [this post](https://community.nodebb.org/topic/10657/emoji-extended-get-error-when-clicking-update-files-on-v1-5-0)

**Comment by julianlam** [comment]
This also seems to occur on initial install as emoji-extended will detect so and try to update emoji-one assets...

**Comment by ghost** [comment]
Hey, sorry for the delay.
Fixed within `nodebb-plugin-emoji-extended@1.2.0`

**Comment by julianlam** [comment]
Hi @frissdiegurke have you published this to npm?
