### ISSUE TITLE
Fix run with ssl

### ISSUE THREAD

**Issue by tungtouch** [NodeBB-Community/nodebb-plugin-emoji-extended#6]
Mixed Content: The page at 'https://xxxx.xx/' was loaded over HTTPS, but requested an insecure image 'http://xxxx.xx:4567/plugins/nodebb-plugin-emoji-extended/images/grinning.png'. This content should also be served over HTTPS.

Pls fix

**Comment by frodesigns** [comment]
Seconding this.

**Comment by yariplus** [comment]
This would have been caused by an invalid url in `config.json`, check your `config.json` and make sure the url is the actual url of the forum.
