### ISSUE TITLE
Emoji require width and height attributes 

### ISSUE THREAD

**Issue by julianlam** [NodeBB-Community/nodebb-plugin-emoji-extended#7]
See: https://what.thedailywtf.com/topic/19419/where-have-the-custom-emojis-gone/94

As emoji load, they cause the page to slowly "march down" 

As emoji are either of identical size or uploaded small images, adding width and height attributes here will resolve the problem.

**Comment by frissdiegurke** [comment]
To be changed within 
 * emoji-cubicopp
 * emoji-one
 * emoji-apple

And I thought `width: auto;` would be a great idea :laughing:

**Comment by julianlam** [comment]
:laughing: Seems like a great idea... but in any case, in emoji-apple I remember you had a setting to specify emoji size, I suppose you can just use that value as width and height?

It's mostly uploaded images, if you add your own static image, that you'd have to save dimensions...

**Comment by julianlam** [comment]
@BenLubar

**Comment by frissdiegurke** [comment]
not published to NPM yet :P going to publish soon, just fixing some other issues before...
